# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testui.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(597, 429)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 591, 421))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.username_edit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.username_edit.setEnabled(False)
        self.username_edit.setReadOnly(False)
        self.username_edit.setObjectName("username_edit")
        self.gridLayout.addWidget(self.username_edit, 1, 0, 1, 1)
        self.image_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.image_label.setFrameShape(QtWidgets.QFrame.Box)
        self.image_label.setLineWidth(1)
        self.image_label.setText("")
        self.image_label.setObjectName("image_label")
        self.gridLayout.addWidget(self.image_label, 1, 0, 1, 1)
        self.set_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.set_label.setFont(font)
        self.set_label.setFocusPolicy(QtCore.Qt.NoFocus)
        self.set_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.set_label.setScaledContents(False)
        self.set_label.setAlignment(QtCore.Qt.AlignCenter)
        self.set_label.setObjectName("set_label")
        self.gridLayout.addWidget(self.set_label, 7, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 6, 0, 1, 1)
        self.radio_0 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radio_0.setChecked(True)
        self.radio_0.setObjectName("radio_0")
        self.gridLayout.addWidget(self.radio_0, 8, 0, 1, 1)
        self.radio_3 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radio_3.setObjectName("radio_3")
        self.gridLayout.addWidget(self.radio_3, 7, 0, 1, 1)
        self.progress_bar = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progress_bar.setBaseSize(QtCore.QSize(0, 10))
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setObjectName("progress_bar")
        self.gridLayout.addWidget(self.progress_bar, 4, 0, 1, 1)
        self.radio_2 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radio_2.setObjectName("radio_2")
        self.gridLayout.addWidget(self.radio_2, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 6, 0, 1, 1)
        self.set_username_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.set_username_button.setObjectName("set_username_button")
        self.gridLayout.addWidget(self.set_username_button, 5, 0, 1, 1)
        self.prev_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.prev_button.setObjectName("prev_button")
        self.gridLayout.addWidget(self.prev_button, 4, 0, 1, 1)
        self.jump_box = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.jump_box.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.jump_box.setAutoFillBackground(True)
        self.jump_box.setObjectName("jump_box")
        self.gridLayout.addWidget(self.jump_box, 3, 0, 1, 1)
        self.position_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.position_label.setFont(font)
        self.position_label.setAlignment(QtCore.Qt.AlignCenter)
        self.position_label.setObjectName("position_label")
        self.gridLayout.addWidget(self.position_label, 3, 0, 1, 1)
        self.next_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.next_button.setObjectName("next_button")
        self.gridLayout.addWidget(self.next_button, 2, 0, 1, 1)
        self.colour_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.colour_label.setAutoFillBackground(True)
        self.colour_label.setText("")
        self.colour_label.setObjectName("colour_label")
        self.gridLayout.addWidget(self.colour_label, 2, 0, 1, 1)
        self.radio_1 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radio_1.setObjectName("radio_1")
        self.gridLayout.addWidget(self.radio_1, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.username_edit.setText(_translate("Dialog", "Username"))
        self.set_label.setText(_translate("Dialog", "set name"))
        self.label_2.setText(_translate("Dialog", "User:"))
        self.radio_0.setText(_translate("Dialog", "Not"))
        self.radio_3.setText(_translate("Dialog", "Definitely"))
        self.radio_2.setText(_translate("Dialog", "Possibly"))
        self.label.setText(_translate("Dialog", "Jump to:"))
        self.set_username_button.setText(_translate("Dialog", "Set"))
        self.prev_button.setText(_translate("Dialog", "Prev"))
        self.position_label.setText(_translate("Dialog", "0"))
        self.next_button.setText(_translate("Dialog", "Next"))
        self.radio_1.setText(_translate("Dialog", "Unlikely"))

