# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'firstui.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(677, 419)
        Dialog.setAutoFillBackground(True)
        self.prev_button = QtWidgets.QPushButton(Dialog)
        self.prev_button.setGeometry(QtCore.QRect(80, 200, 111, 51))
        self.prev_button.setObjectName("prev_button")
        self.next_button = QtWidgets.QPushButton(Dialog)
        self.next_button.setGeometry(QtCore.QRect(450, 200, 111, 51))
        self.next_button.setObjectName("next_button")
        self.position_label = QtWidgets.QLabel(Dialog)
        self.position_label.setGeometry(QtCore.QRect(290, 310, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.position_label.setFont(font)
        self.position_label.setAlignment(QtCore.Qt.AlignCenter)
        self.position_label.setObjectName("position_label")
        self.progress_bar = QtWidgets.QProgressBar(Dialog)
        self.progress_bar.setGeometry(QtCore.QRect(50, 360, 151, 41))
        self.progress_bar.setBaseSize(QtCore.QSize(0, 10))
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setObjectName("progress_bar")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(234, 365, 57, 14))
        self.label.setObjectName("label")
        self.set_label = QtWidgets.QLabel(Dialog)
        self.set_label.setGeometry(QtCore.QRect(200, 10, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.set_label.setFont(font)
        self.set_label.setFocusPolicy(QtCore.Qt.NoFocus)
        self.set_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.set_label.setScaledContents(False)
        self.set_label.setAlignment(QtCore.Qt.AlignCenter)
        self.set_label.setObjectName("set_label")
        self.jump_box = QtWidgets.QLineEdit(Dialog)
        self.jump_box.setGeometry(QtCore.QRect(290, 360, 61, 21))
        self.jump_box.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.jump_box.setAutoFillBackground(True)
        self.jump_box.setObjectName("jump_box")
        self.image_label = QtWidgets.QLabel(Dialog)
        self.image_label.setGeometry(QtCore.QRect(230, 130, 191, 171))
        self.image_label.setFrameShape(QtWidgets.QFrame.Box)
        self.image_label.setLineWidth(1)
        self.image_label.setText("")
        self.image_label.setObjectName("image_label")
        self.last_rated_button = QtWidgets.QPushButton(Dialog)
        self.last_rated_button.setGeometry(QtCore.QRect(240, 390, 141, 31))
        self.last_rated_button.setObjectName("last_rated_button")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(460, 375, 56, 13))
        self.label_2.setObjectName("label_2")
        self.username_edit = QtWidgets.QLineEdit(Dialog)
        self.username_edit.setEnabled(False)
        self.username_edit.setGeometry(QtCore.QRect(500, 370, 91, 21))
        self.username_edit.setReadOnly(False)
        self.username_edit.setObjectName("username_edit")
        self.colour_label = QtWidgets.QLabel(Dialog)
        self.colour_label.setGeometry(QtCore.QRect(220, 120, 211, 191))
        self.colour_label.setAutoFillBackground(True)
        self.colour_label.setText("")
        self.colour_label.setObjectName("colour_label")
        self.set_username_button = QtWidgets.QPushButton(Dialog)
        self.set_username_button.setGeometry(QtCore.QRect(590, 370, 51, 32))
        self.set_username_button.setObjectName("set_username_button")
        self.radio_0 = QtWidgets.QRadioButton(Dialog)
        self.radio_0.setGeometry(QtCore.QRect(150, 90, 97, 18))
        self.radio_0.setChecked(True)
        self.radio_0.setObjectName("radio_0")
        self.radio_1 = QtWidgets.QRadioButton(Dialog)
        self.radio_1.setGeometry(QtCore.QRect(210, 90, 97, 18))
        self.radio_1.setObjectName("radio_1")
        self.radio_3 = QtWidgets.QRadioButton(Dialog)
        self.radio_3.setGeometry(QtCore.QRect(390, 90, 97, 18))
        self.radio_3.setObjectName("radio_3")
        self.radio_2 = QtWidgets.QRadioButton(Dialog)
        self.radio_2.setGeometry(QtCore.QRect(300, 90, 97, 18))
        self.radio_2.setObjectName("radio_2")
        self.colour_label.raise_()
        self.prev_button.raise_()
        self.next_button.raise_()
        self.position_label.raise_()
        self.progress_bar.raise_()
        self.label.raise_()
        self.set_label.raise_()
        self.jump_box.raise_()
        self.image_label.raise_()
        self.last_rated_button.raise_()
        self.label_2.raise_()
        self.username_edit.raise_()
        self.set_username_button.raise_()
        self.radio_0.raise_()
        self.radio_1.raise_()
        self.radio_3.raise_()
        self.radio_2.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "LensRater"))
        Dialog.setToolTip(_translate("Dialog", "Col\'s lens rater"))
        self.prev_button.setText(_translate("Dialog", "Prev"))
        self.next_button.setText(_translate("Dialog", "Next"))
        self.position_label.setText(_translate("Dialog", "0"))
        self.label.setText(_translate("Dialog", "Jump to:"))
        self.set_label.setText(_translate("Dialog", "set name"))
        self.last_rated_button.setText(_translate("Dialog", "Go to last rated"))
        self.label_2.setText(_translate("Dialog", "User:"))
        self.username_edit.setText(_translate("Dialog", "Username"))
        self.set_username_button.setText(_translate("Dialog", "Set"))
        self.radio_0.setText(_translate("Dialog", "Not"))
        self.radio_1.setText(_translate("Dialog", "Unlikely"))
        self.radio_3.setText(_translate("Dialog", "Definitely"))
        self.radio_2.setText(_translate("Dialog", "Possibly"))

